import { User } from './mongoUtils.mjs';
const flows = {
  '/stripe-cancel-subscription':[

  ],
  '/stripe-change-subscription':[

  ],
  '/stripe-create-subscription':[

  ],
  '/stripe-retrieve-subscription':[

  ],
}
const objects = {
  'invoiceitem.created': {},
  'invoiceitem.deleted': {},
  'invoiceitem.updated': {},
  'invoice.deleted': {},
  'invoice.created': {},
  'invoice.finalization_failed': {},
  'invoice.finalized': {},
  'invoice.marked_uncollectible': {},
  'invoice.paid': {},
  'invoice.payment_action_required': {},
  'invoice.payment_failed': {},
  'invoice.payment_succeeded': {},
  'invoice.sent': {},
  'invoice.upcoming': {},
  'invoice.updated': {
    id: 'evt_1MUEtTD1nNXXpxulHOIlRbnh',
    object: 'event',
    api_version: '2022-11-15',
    created: 1674675866,
    data: {
      object: {
        id: 'in_1MUESgD1nNXXpxulS8iKQP3G',
        object: 'invoice',
        account_country: 'US',
        account_name: 'td1.me',
        account_tax_ids: null,
        amount_due: 3999,
        amount_paid: 0,
        amount_remaining: 3999,
        application: null,
        application_fee_amount: null,
        attempt_count: 0,
        attempted: false,
        auto_advance: false,
        automatic_tax: [Object],
        billing_reason: 'subscription_create',
        charge: null,
        collection_method: 'charge_automatically',
        created: 1674674206,
        currency: 'usd',
        custom_fields: null,
        customer: 'cus_NEVap82sQScdLo',
        customer_address: null,
        customer_email: 'mooncodev@gmail.com',
        customer_name: null,
        customer_phone: null,
        customer_shipping: null,
        customer_tax_exempt: 'none',
        customer_tax_ids: [],
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [],
        description: null,
        discount: null,
        discounts: [],
        due_date: null,
        ending_balance: 0,
        footer: null,
        from_invoice: null,
        hosted_invoice_url: 'https://invoice.stripe.com/i/acct_1MQIToD1nNXXpxul/test_YW0kLK0oRsv?s=ap',
        invoice_pdf: 'https://pay.stripe.com/invoice/acct_1MQIToD1nNXXpxul/test_kLK0oRsv/pdf?s=ap'
        ,
        last_finalization_error: null,
        latest_revision: null,
        lines: [Object],
        livemode: false,
        metadata: {},
        next_payment_attempt: null,
        number: '9C7794C2-0002',
        on_behalf_of: null,
        paid: false,
        paid_out_of_band: false,
        payment_intent: 'pi_3MUESgD1nNXXpxul0FnztKTe',
        payment_settings: [Object],
        period_end: 1674674206,
        period_start: 1674674206,
        post_payment_credit_notes_amount: 0,
        pre_payment_credit_notes_amount: 0,
        quote: null,
        receipt_number: null,
        rendering_options: null,
        starting_balance: 0,
        statement_descriptor: null,
        status: 'void',
        status_transitions: [Object],
        subscription: 'sub_1MUESgD1nNXXpxuluxJuCHHS',
        subtotal: 3999,
        subtotal_excluding_tax: 3999,
        tax: null,
        test_clock: null,
        total: 3999,
        total_discount_amounts: [],
        total_excluding_tax: 3999,
        total_tax_amounts: [],
        transfer_data: null,
        webhooks_delivered_at: 1674674207
      },
      previous_attributes: { status: 'open', status_transitions: [Object] }
    },
    livemode: false,
    pending_webhooks: 2,
    request: { id: 'req_m7biOf5n071Gfz', idempotency_key: null },
    type: 'invoice.updated'
  },
  'invoice.voided': {
    id: 'evt_1MUEtTD1nNXXpxulrJn2bn67',
    object: 'event',
    api_version: '2022-11-15',
    created: 1674675866,
    data: {
      object: {
        id: 'in_1MUESgD1nNXXpxulS8iKQP3G',
        object: 'invoice',
        account_country: 'US',
        account_name: 'td1.me',
        account_tax_ids: null,
        amount_due: 3999,
        amount_paid: 0,
        amount_remaining: 3999,
        application: null,
        application_fee_amount: null,
        attempt_count: 0,
        attempted: false,
        auto_advance: false,
        automatic_tax: [Object],
        billing_reason: 'subscription_create',
        charge: null,
        collection_method: 'charge_automatically',
        created: 1674674206,
        currency: 'usd',
        custom_fields: null,
        customer: 'cus_NEVap82sQScdLo',
        customer_address: null,
        customer_email: 'mooncodev@gmail.com',
        customer_name: null,
        customer_phone: null,
        customer_shipping: null,
        customer_tax_exempt: 'none',
        customer_tax_ids: [],
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [],
        description: null,
        discount: null,
        discounts: [],
        due_date: null,
        ending_balance: 0,
        footer: null,
        from_invoice: null,
        hosted_invoice_url: 'https://invoice.stripe.com/i/acct_1MQIToD1nNXXpxul/test_Y00kLK0oRsv?s=ap',
        invoice_pdf: 'https://pay.stripe.com/invoice/acct_1MQIToD1nNXXpxul/test_YWNjK0oRsv/pdf?s=ap',
        last_finalization_error: null,
        latest_revision: null,
        lines: [Object],
        livemode: false,
        metadata: {},
        next_payment_attempt: null,
        number: '9C7794C2-0002',
        on_behalf_of: null,
        paid: false,
        paid_out_of_band: false,
        payment_intent: 'pi_3MUESgD1nNXXpxul0FnztKTe',
        payment_settings: [Object],
        period_end: 1674674206,
        period_start: 1674674206,
        post_payment_credit_notes_amount: 0,
        pre_payment_credit_notes_amount: 0,
        quote: null,
        receipt_number: null,
        rendering_options: null,
        starting_balance: 0,
        statement_descriptor: null,
        status: 'void',
        status_transitions: [Object],
        subscription: 'sub_1MUESgD1nNXXpxuluxJuCHHS',
        subtotal: 3999,
        subtotal_excluding_tax: 3999,
        tax: null,
        test_clock: null,
        total: 3999,
        total_discount_amounts: [],
        total_excluding_tax: 3999,
        total_tax_amounts: [],
        transfer_data: null,
        webhooks_delivered_at: 1674674207
      }
    },
    livemode: false,
    pending_webhooks: 2,
    request: { id: 'req_m7biOf5n071Gfz', idempotency_key: null },
    type: 'invoice.voided'
  },
  'subscription_schedule.aborted': {},
  'subscription_schedule.canceled': {},
  'subscription_schedule.completed': {},
  'subscription_schedule.created': {},
  'subscription_schedule.expiring': {},
  'subscription_schedule.released': {},
  'subscription_schedule.updated': {},

  'balance.available': {},
  'cash_balance.funds_available': {},
  'charge.captured': {},
  'charge.expired': {},
  'charge.failed': {},
  'charge.pending': {},
  'charge.refunded': {},
  'charge.succeeded': {},
  'charge.updated': {},
  'charge.dispute.closed': {},
  'charge.dispute.created': {},
  'charge.dispute.funds_reinstated': {},
  'charge.dispute.funds_withdrawn': {},
  'charge.dispute.updated': {},
  'charge.refund.updated': {},
  'checkout.session.async_payment_failed': {},
  'checkout.session.async_payment_succeeded': {},
  'checkout.session.completed': {},
  'checkout.session.expired': {},
  'customer.created': {},
  'customer.deleted': {},
  'customer.updated': {},
  'customer.subscription.created': {},
  'customer.subscription.deleted': {},
  'customer.subscription.pending_update_applied': {},
  'customer.subscription.pending_update_expired': {},
  'customer.subscription.trial_will_end': {},
  'customer.subscription.updated': {
    id: 'evt_1MUEtTD1nNXXpxulIQzZ2f2v',
    object: 'event',
    api_version: '2022-11-15',
    created: 1674675866,
    data: {
      object: {
        id: 'sub_1MUESgD1nNXXpxuluxJuCHHS',
        object: 'subscription',
        application: null,
        application_fee_percent: null,
        automatic_tax: [Object],
        billing_cycle_anchor: 1674674206,
        billing_thresholds: null,
        cancel_at: null,
        cancel_at_period_end: false,
        canceled_at: 1674675866,
        collection_method: 'charge_automatically',
        created: 1674674206,
        currency: 'usd',
        current_period_end: 1677352606,
        current_period_start: 1674674206,
        customer: 'cus_NEVap82sQScdLo',
        days_until_due: null,
        default_payment_method: null,
        default_source: null,
        default_tax_rates: [],
        description: null,
        discount: null,
        ended_at: 1674675866,
        items: [Object],
        latest_invoice: 'in_1MUESgD1nNXXpxulS8iKQP3G',
        livemode: false,
        metadata: {},
        next_pending_invoice_item_invoice: null,
        on_behalf_of: null,
        pause_collection: null,
        payment_settings: [Object],
        pending_invoice_item_interval: null,
        pending_setup_intent: null,
        pending_update: null,
        plan: [Object],
        quantity: 1,
        schedule: null,
        start_date: 1674674206,
        status: 'incomplete_expired',
        test_clock: null,
        transfer_data: null,
        trial_end: null,
        trial_start: null
      },
      previous_attributes: { canceled_at: null, ended_at: null, status: 'incomplete' }
    },
    livemode: false,
    pending_webhooks: 2,
    request: { id: 'req_m7biOf5n071Gfz', idempotency_key: null },
    type: 'customer.subscription.updated'
  },
  'customer_cash_balance_transaction.created': {},
  'order.created': {},
  'payment_intent.amount_capturable_updated': {},
  'payment_intent.canceled': {
    id: 'evt_3MUESgD1nNXXpxul0yXzDDSd',
    object: 'event',
    api_version: '2022-11-15',
    created: 1674675866,
    data: {
      object: {
        id: 'pi_3MUESgD1nNXXpxul0FnztKTe',
        object: 'payment_intent',
        amount: 3999,
        amount_capturable: 0,
        amount_details: [Object],
        amount_received: 0,
        application: null,
        application_fee_amount: null,
        automatic_payment_methods: null,
        canceled_at: 1674675866,
        cancellation_reason: 'void_invoice',
        capture_method: 'automatic',
        client_secret: 'pi_3MUESgD1nNXXpxul0FnztKTe_secret_YhfXqZOcuXLOzR96pkzHT8KIo',
        confirmation_method: 'automatic',
        created: 1674674206,
        currency: 'usd',
        customer: 'cus_NEVap82sQScdLo',
        description: 'Subscription creation',
        invoice: 'in_1MUESgD1nNXXpxulS8iKQP3G',
        last_payment_error: null,
        latest_charge: null,
        livemode: false,
        metadata: {},
        next_action: null,
        on_behalf_of: null,
        payment_method: null,
        payment_method_options: [Object],
        payment_method_types: [Array],
        processing: null,
        receipt_email: 'mooncodev@gmail.com',
        review: null,
        setup_future_usage: 'off_session',
        shipping: null,
        source: null,
        statement_descriptor: null,
        statement_descriptor_suffix: null,
        status: 'canceled',
        transfer_data: null,
        transfer_group: null
      }
    },
    livemode: false,
    pending_webhooks: 2,
    request: { id: 'req_m7biOf5n071Gfz', idempotency_key: null },
    type: 'payment_intent.canceled'
  },
  'payment_intent.created': {},
  'payment_intent.partially_funded': {},
  'payment_intent.payment_failed': {},
  'payment_intent.processing': {},
  'payment_intent.requires_action': {},
  'payment_intent.succeeded': {},
  'payment_method.attached': {},
  'payment_method.automatically_updated': {},
  'payment_method.detached': {},
  'payment_method.updated': {},
  'radar.early_fraud_warning.created': {},
  'radar.early_fraud_warning.updated': {},
  'review.closed': {},
  'review.opened': {},

}
